"""Shared constants for lottery research."""

MAX_ENSEMBLE_CONTRIBUTORS = 5
DEFAULT_EVALUATION_SIZE = 3
DEFAULT_PICK_SIZE = 5
MAX_PICK_SIZE = 20
MAX_LLM_REQUEST_DELAY_MS = 30000
DEFAULT_LLM_RETRY_COUNT = 2
DEFAULT_LLM_RETRY_BACKOFF_MS = 1500
DEFAULT_LLM_PARALLELISM = 8
DEFAULT_ISSUE_PARALLELISM = 1
MAX_LLM_RETRY_COUNT = 5
MAX_LLM_RETRY_BACKOFF_MS = 15000
DEFAULT_AGENT_DIALOGUE_ENABLED = True
DEFAULT_AGENT_DIALOGUE_ROUNDS = 1
MAX_AGENT_DIALOGUE_ROUNDS = 5
MAX_SOCIAL_AGENT_COUNT = 6
WORLD_WARMUP_ISSUES = 3
DEFAULT_LIVE_INTERVIEW_ENABLED = True
DEFAULT_BUDGET_YUAN = 50
MIN_BUDGET_YUAN = 2
MAX_BUDGET_YUAN = 500
ALTERNATE_NUMBER_COUNT = 3
RANKED_SCORE_PREVIEW = 10
PROCESS_PREVIEW_ISSUES = 5
GRAPH_RECENT_DRAW_LIMIT = 24
PRIMARY_GROUPS = ("data", "metaphysics", "hybrid")
SOCIAL_GROUP = "social"
JUDGE_GROUP = "judge"
LEGACY_RUNTIME_MODE = "legacy"
WORLD_V1_RUNTIME_MODE = "world_v1"
WORLD_V2_MARKET_RUNTIME_MODE = "world_v2_market"
RUNTIME_MODES = (LEGACY_RUNTIME_MODE, WORLD_V1_RUNTIME_MODE, WORLD_V2_MARKET_RUNTIME_MODE)
LOCAL_GRAPH_MODE = "local"
KUZU_GRAPH_MODE = "kuzu"
ZEP_GRAPH_MODE = "zep"
GRAPH_MODES = (LOCAL_GRAPH_MODE, KUZU_GRAPH_MODE, ZEP_GRAPH_MODE)
WORLD_PHASES = (
    "opening",
    "interviews",
    "public_debate",
    "judge_synthesis",
    "purchase_committee",
    "settle",
)
WORLD_V2_PHASES = (
    "generator_opening",
    "social_propagation",
    "market_rerank",
    "plan_synthesis",
    "handbook_final_decision",
    "settlement",
    "postmortem",
)
